#! /bin/bash 

# Checking arguments
[[ $# -gt 0 ]] || printf "\nNo URL was specified!\nExiting..\n\n";


TEMP_FILE='URL_list'; 
URL=$1; # the url where the PDF files are listed
BASE_URL=$2; #Optional: the base URL in case the pdf urls on the page
            # are not complete
export BASE_URL # to be used in perl command

curl $URL | grep "\.pdf" > $TEMP_FILE;
perl -pi -e 's/^.*?<a href="(.*?\.pdf)">.*/\1/gi' $TEMP_FILE;
perl -i -e 'print $ENV{BASE_URL},$_ while <>' $TEMP_FILE;
wget --no-parent -i $TEMP_FILE;
rm $TEMP_FILE;
